# What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

# Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

# 1) Creating Numpy Arrays
### Steps1 : Import Numpy 

In [5]:
# np.array
import numpy as np


### Steps2 : Types of Array 

## A) 1-D array

In [6]:
# 1) One-D array (1-D array) also know as Vector
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


## B) 2-D array

In [20]:
"""
2) Two & Three - D array (2D,3D) also called as Matrix 
     
     A) 2-D Array (it has ROWS and Columns )
"""


b = np.array([[1,2,3],[4,5,6]]) # 2 rows and 3 columns
print(b)

[[1 2 3]
 [4 5 6]]


## C) 3-D array

In [14]:
# 3-D Array also called as Tensor
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Using Different Types of datatypes

In [19]:
# Dtype we can make array of our datatype array

f = np.array([1,2,3],dtype = float)
print(f)

bo = np.array([1,2,3],dtype = bool)
print(bo) #Any non-zero value python make True

com = np.array([1,2,3],dtype = complex)
print(com)

[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


## 2) arange - Second type which is used to create array work same as range

In [21]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

### a) with reshape function - Convert given numpy array to different shape 
### Condition ---> " PRODUCT should be EQUAL "

In [27]:
np.arange(1,11)

#Converting this shape of (5,2) --> we get Matrix 
np.arange(1,11).reshape(5,2) 

np.arange(1,13).reshape(3,4) 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### b) np.ones and np.zeros

In [31]:
"""
np.ones --> used to create an array which consist of 1 also its is in 'TUPLE' 

if we want to immidiately initiazed array used in NLP weight 
"""
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
"""
np.zeros --> used to create an array which consist of 0 also its is in 'TUPLE' 
"""

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### c) np.random --> create array of random values between 0 & 1

In [33]:
np.random.random((3,4))

array([[0.00589816, 0.71681175, 0.59265648, 0.01008518],
       [0.57247999, 0.49918335, 0.55758666, 0.64997994],
       [0.96989429, 0.65631997, 0.50293902, 0.43801504]])

### d) np.linspace( Lower range ,Upper ,No's of item to generate)--> linearly space ( used to generate a point between Lower and Upper in 'EQUAL DISTANCE' )

#### using to ML graph ploting


np.linspace(-10,10,10)

np.linspace(-10,10,10,dtype = int)

### e) np.identity --> create a identity Matrix

In [37]:
np.identity(3) # 3 x 3 matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 2) Array Attributes

In [42]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1) # vector
print(a2) # Matrix
print(a3) # Vectors

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


### 1) ndim --> Numbers of Dimensions
#### used to finds it dimensions

In [48]:
print(a1.ndim,"- D")
print(a2.ndim,"- D")
print(a3.ndim,"- D")

1 - D
2 - D
3 - D


### 2) shape
#### used to shape it dimensions eg how manys Rows and Columns in matrix
### IN 3-D (No's of 2-d arrays inside, Every array ROWS,Every array COLUMNS  )

In [49]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


### 3) SIZE  
#### used to finds No's of ITEMS inside array

In [50]:
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


### 4) ITEMSIZE  
#### used to tell how memory occupy by every items
#### 32 take 4 bytes, 64 take 8 bytes

In [51]:
print(a1.itemsize) 
print(a2.itemsize)
print(a3.itemsize)

4
8
4


### 5) DTYPE  
#### used to finds datatype of elements

In [52]:
print(a1.dtype) 
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# 3) Changing Datatype

### astype - to reduce its datatypes bytes eg convert 1 datatype to reduce form 10gb to 7gb

In [55]:
a1.dtype

dtype('int32')

In [58]:
a1.astype(np.int64)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [60]:
a1.dtype

dtype('int32')

# Array Operations - used to apply mathemathical logic

In [62]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


## Types of Operations
### a) Scaler operations --> on single numpy we only work with 1 scaler
### b) Vectors Operations

In [66]:
a1 * 2 # a1 --> matrix, 2 --> scaler
a1 + 2
a1 - 2
a1 / 2
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

### Relation Operator(< , >, ==,  >= , <=)


In [70]:
a2 > 5 # Itemwise Comparison
a2 > 25
a2 > 15

a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

### Vector Operations

In [72]:
a1 + a2 # IF same shape then only
a1 - a2
a1 * a2
a1 / a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

# Array Functions

In [73]:
a1 = np.random.random((3,3))

array([[ 4., 26.,  9.],
       [50., 46., 96.],
       [36.,  5.,  6.]])

## 1) Round  

In [74]:
a1 = np.round(a1*100)
a1

array([[ 400., 2600.,  900.],
       [5000., 4600., 9600.],
       [3600.,  500.,  600.]])

# 2)  max/min/sum/prod

In [88]:
np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1)


# to find every row minimum 0 -> Column, 1-> row
np.max(a1,axis = 1)
np.min(a1,axis = 1)
np.prod(a1,axis = 1)

array([9.360e+08, 2.208e+11, 1.080e+09])

# 3) mean/median/std/var

In [91]:
np.mean(a1, axis = 1)
np.median(a1, axis = 1)
np.std(a1, axis = 1)
np.var(a1, axis = 1)

array([ 886666.66666667, 5146666.66666667, 2068888.88888889])

# 4)  trigonomoetric functions

In [92]:
np.sin(a1)
np.cos(a1)
np.tan(a1)

array([[ 1.61988443, -2.89981476, 15.06193125],
       [-6.3876422 ,  0.85667264, -0.85458412],
       [-0.27157691,  0.52924386, -0.04422564]])

# 5) dot product --> 2 matrixes betwen dot product
### condition  (3, 4    4 , 3) first matrix col and 2nd matrix row should be same

In [94]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

# 6) log and exponents

In [98]:
np.log(a1)
np.exp(a1)

C:\Users\PC\AppData\Local\Temp\ipykernel_2496\451780190.py:2: RuntimeWarning: overflow encountered in exp
  np.exp(a1)


array([[5.22146969e+173,             inf,             inf],
       [            inf,             inf,             inf],
       [            inf, 1.40359222e+217, 3.77302030e+260]])

# 7) round/floor/ceil

In [102]:
np.random.random((2,3))*100

np.round(np.random.random((2,3))*100) # will round off nearby
np.floor(np.random.random((2,3))*100) # before pehle wala int
np.ceil(np.random.random((2,3))*100)  # after aage wala int

array([[95., 62., 74.],
       [13., 19., 38.]])

# Indexing  and Slicing 

### 1) Indexing (we can fetch only 1 item)

In [103]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [105]:
# get last item
a1[-1] #negative indexing right to left

# get first item
a1[0] # Postive indexing left to right 

0

In [106]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
#Get 6  so [row,col]
a2[1,2]

6

In [109]:
#Get 11 or 4
print(a2[2,3]) # 11
a2[1,0] #4

11


4

### In 3D 
#### 3D made from 2D and 2D made from 1D

In [110]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [112]:
#Get 5
a3[1,0,1] #[2d array ,row ,col]

5

In [114]:
#Get 2
a3[0,1,0]

2

In [115]:
#Get 0
a3[0,0,0]

0

In [117]:
#Get 6
a3[1,1,0]

6

### 2) Slicing (we can fetch multiple item)

In [118]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
# Get 2 ,3, 4
a1[2:5]
a1[2:5:2]

array([2, 4])

### 2-D [ : , column ] --> get col (we want every rows) ,  [ row, : ] --> get row (we want every columns)

In [123]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
# get only 1 row
a2[0,:]

array([0, 1, 2, 3])

In [127]:
# get 3 col
a2[:,2]

array([ 2,  6, 10])

In [128]:
# get 5 6 and 9 10
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [136]:
# get 0 3 and 8 11
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [144]:
# get 1 3 and 9 11
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [150]:
# get 4 7
a2[1, ::3]

array([4, 7])

In [151]:
# get 123 567
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

### 3-D array

In [152]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [172]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [173]:
"""
get [[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])
"""

a3[1,:,:]
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [174]:
"""
get [[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

"""


a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

"""
get [ 3,  4,  5]

"""

a3[0,1]

In [176]:
"""
get 10
    13
    16

"""
a3[1,:,1]

array([10, 13, 16])

In [177]:
"""
get 22, 23,
    25, 26
"""

a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [182]:
 """
get 0, 2,
    18,20
"""
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [187]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [189]:
a2
# It will print full row
for i in a2:
    print(i)


[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [194]:
a3
# It will print 2d array
for i in a3:
    print(i)
    
# to print individual element
for i in np.nditer(a3):
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping
<ol>
    <li> Range </li>
    <li>Transpose --> convert ROW to Column </li>
    <li> ravel --> any dimension array convert it into 1-D </li>
</ol>

In [196]:
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [199]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking --> to merge 2 or more Numpy array
<ol>
    <li>Horizontal Stacking</li>
    <li>Vertical Stacking</li>
</ol>

<h3>Used when we have multiple data source to merge</h3>

In [205]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a4
a5

#1) Horizontal Stacking
print(np.hstack((a4,a5)))
print(np.hstack((a4,a5)))

#2) Vertical Stacking
print(np.vstack((a4,a5)))

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


# Splitting -->  Opposite of Stacking
<ol>
    <li>Horizontal Splitting --> | it cut matrix</li>
        <li>Vertical Splitting -->  -- it cut matrix</li>
</ol>

In [208]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [206]:
np.hsplit(a4,2) # 2 --> in how may parts

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [209]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [210]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]